export const skillList = [
  { id: 0, name: "Acrobatics", type: "acrobatics", link: ["rfl"], tnc: "SB/7", page: "P.141" },
  { id: 1, name: "Acting", type: "acting", link: ["cha"], tnc: "CB/8", page: "P.142" },
  {
    id: 2,
    name: "Administration",
    type: "administration",
    link: ["int", "wil"],
    tnc: "SA/8",
    page: "P.143",
  },
  {
    id: 3,
    name: "Animal Handling",
    type: "animalHandling",
    link: ["wil"],
    tnc: "SB/7",
    page: "P.143",
  },
  { id: 4, name: "Appraisal", type: "appraisal", link: ["int"], tnc: "CB/8", page: "P.143" },
  { id: 5, name: "Archery", type: "archery", link: ["dex"], tnc: "SB/7", page: "P.143" },
  { id: 6, name: "Art", type: "art", link: ["dex"], tnc: "CB/8", page: "P.144" },
  { id: 7, name: "Artillery", type: "artillery", link: ["int", "wil"], tnc: "SA/8", page: "P.144" },
  { id: 8, name: "Career", type: "career", link: ["int"], tnc: "SB/7", page: "P.144" },
  { id: 9, name: "Climbing", type: "climbing", link: ["dex"], tnc: "SB/7", page: "P.144" },
  {
    id: 10,
    name: "Communications",
    type: "communications",
    link: ["int"],
    tnc: "SB/7",
    page: "P.144",
  },
  { id: 11, name: "Computers", type: "computers", link: ["int"], tnc: "CA/9", page: "P.145" },
  {
    id: 12,
    name: "Cryptography",
    type: "cryptography",
    link: ["int", "wil"],
    tnc: "CA/9",
    page: "P.145",
  },
  {
    id: 13,
    name: "Demolitions",
    type: "demolitions",
    link: ["dex", "int"],
    tnc: "CA/9",
    page: "P.146",
  },
  {
    id: 14,
    name: "Disguise (+1 kit)",
    type: "disguiseKit",
    link: ["cha"],
    tnc: "SB/7",
    page: "P.146",
  },
  { id: 15, name: "Driving", type: "driving", link: ["rfl", "dex"], tnc: "SA/8", page: "P.146" },
  {
    id: 16,
    name: "Escape Artist",
    type: "escapeArtist",
    link: ["str", "dex"],
    tnc: "CA/9",
    page: "P.147",
  },
  { id: 17, name: "Forgery", type: "forgery", link: ["dex", "int"], tnc: "SA/8", page: "P.147" },
  { id: 18, name: "Gunnery", type: "gunnery", link: ["rfl", "dex"], tnc: "SA/8", page: "P.147" },
  { id: 19, name: "Interest", type: "interest", link: ["int"], tnc: "CB/8", page: "P.147" },
  {
    id: 20,
    name: "Interrogation",
    type: "interrogation",
    link: ["wil", "cha"],
    tnc: "CA/9",
    page: "P.148",
  },
  {
    id: 21,
    name: "Investigation",
    type: "investigation",
    link: ["int", "wil"],
    tnc: "CA/9",
    page: "P.148",
  },
  { id: 22, name: "Language", type: "language", link: ["int", "cha"], tnc: "SA/8", page: "P.148" },
  {
    id: 23,
    name: "Leadership",
    type: "leadership",
    link: ["wil", "cha"],
    tnc: "SA/8",
    page: "P.148",
  },
  { id: 24, name: "Martial Arts", type: "martialArts", link: ["rfl"], tnc: "SB/7", page: "P.149" },
  { id: 25, name: "MedTech", type: "medTech", link: ["int"], tnc: "SB/7", page: "P.149" },
  {
    id: 26,
    name: "Melee Weapons",
    type: "meleeWeapons",
    link: ["rfl"],
    tnc: "SB/7",
    page: "P.149",
  },
  { id: 27, name: "Navigation", type: "navigation", link: ["int"], tnc: "SB/7", page: "P.150" },
  { id: 28, name: "Negotiation", type: "negotiation", link: ["cha"], tnc: "CB/8", page: "P.150" },
  { id: 29, name: "Perception", type: "perception", link: ["int"], tnc: "SB/7", page: "P.151" },
  { id: 30, name: "Piloting", type: "piloting", link: ["rfl", "dex"], tnc: "SA/8", page: "P.151" },
  {
    id: 31,
    name: "Prestidigitation",
    type: "prestidigitation",
    link: ["dex"],
    tnc: "SB/7",
    page: "P.152",
  },
  { id: 32, name: "Protocol", type: "protocol", link: ["wil", "cha"], tnc: "CA/9", page: "P.152" },
  { id: 33, name: "Running", type: "running", link: ["rfl"], tnc: "SB/7", page: "P.152" },
  { id: 34, name: "Science", type: "science", link: ["int", "wil"], tnc: "CA/9", page: "P.153" },
  {
    id: 35,
    name: "Security Systems",
    type: "securitySystems",
    link: ["dex", "int"],
    tnc: "CA/9",
    page: "P.153",
  },
  {
    id: 36,
    name: "Sensor Operations",
    type: "sensorOperations",
    link: ["int", "wil"],
    tnc: "CA/9",
    page: "P.153",
  },
  { id: 37, name: "Small Arms", type: "smallArms", link: ["dex"], tnc: "SB/7", page: "P.153" },
  { id: 38, name: "Stealth", type: "stealth", link: ["rfl", "int"], tnc: "SB/7", page: "P.154" },
  { id: 39, name: "Strategy", type: "strategy", link: ["int", "wil"], tnc: "CA/9", page: "P.154" },
  { id: 40, name: "Streetwise", type: "streetwise", link: ["cha"], tnc: "SB/7", page: "P.154" },
  {
    id: 41,
    name: "Support Weapons",
    type: "supportWeapons",
    link: ["dex"],
    tnc: "SB/7",
    page: "P.154",
  },
  { id: 42, name: "Surgery", type: "surgery", link: ["dex", "int"], tnc: "CA/9", page: "P.154" },
  { id: 43, name: "Survival", type: "survival", link: ["bod", "int"], tnc: "SB/7", page: "P.156" },
  { id: 44, name: "Swimming", type: "swimming", link: ["str"], tnc: "SB/7", page: "P.156" },
  { id: 45, name: "Tactics", type: "tactics", link: ["int", "wil"], tnc: "CA/9", page: "P.156" },
  {
    id: 46,
    name: "Technician",
    type: "technician",
    link: ["dex", "int"],
    tnc: "CA/9",
    page: "P.157",
  },
  {
    id: 47,
    name: "Thrown Weapons",
    type: "thrownWeapons",
    link: ["dex"],
    tnc: "SB/7",
    page: "P.158",
  },
  { id: 48, name: "Tracking", type: "tracking", link: ["int", "wil"], tnc: "CA/9", page: "P.158" },
  { id: 49, name: "Training", type: "training", link: ["int", "cha"], tnc: "CA/9", page: "P.159" },
  {
    id: 50,
    name: "Zero-G Operations",
    type: "zeroGOperations",
    link: ["rfl"],
    tnc: "SB/7",
    page: "P.159",
  },
];

/*
export const skillList = [
  { name: "Acrobatics", link: ["rfl"], tnc: "SB/7", page: "P.141" },
  { name: "Acting", link: ["cha"], tnc: "CB/8", page: "P.142" },
  { name: "Administration", link: ["int", "wil"], tnc: "SA/8", page: "P.143" },
  { name: "Animal Handling", link: ["wil"], tnc: "SB/7", page: "P.143" },
  { name: "Appraisal", link: ["int"], tnc: "CB/8", page: "P.143" },
  { name: "Archery", link: ["dex"], tnc: "SB/7", page: "P.143" },
  { name: "Art", link: ["dex"], tnc: "CB/8", page: "P.144" },
  { name: "Artillery", link: ["int", "wil"], tnc: "SA/8", page: "P.144" },
  { name: "Career", link: ["int"], tnc: "SB/7", page: "P.144" },
  { name: "Climbing", link: ["dex"], tnc: "SB/7", page: "P.144" },
  { name: "Communications", link: ["int"], tnc: "SB/7", page: "P.144" },
  { name: "Computers", link: ["int"], tnc: "CA/9", page: "P.145" },
  { name: "Cryptography", link: ["int", "wil"], tnc: "CA/9", page: "P.145" },
  { name: "Demolitions", link: ["dex", "int"], tnc: "CA/9", page: "P.146" },
  { name: "Disguise (+1 kit)", link: ["cha"], tnc: "SB/7", page: "P.146" },
  { name: "Driving", link: ["rfl", "dex"], tnc: "SA/8", page: "P.146" },
  { name: "Escape Artist", link: ["str", "dex"], tnc: "CA/9", page: "P.147" },
  { name: "Forgery", link: ["dex", "int"], tnc: "SA/8", page: "P.147" },
  { name: "Gunnery", link: ["rfl", "dex"], tnc: "SA/8", page: "P.147" },
  { name: "Interest", link: ["int"], tnc: "CB/8", page: "P.147" },
  { name: "Interrogation", link: ["wil", "cha"], tnc: "CA/9", page: "P.148" },
  { name: "Investigation", link: ["int", "wil"], tnc: "CA/9", page: "P.148" },
  { name: "Language", link: ["int", "cha"], tnc: "SA/8", page: "P.148" },
  { name: "Leadership", link: ["wil", "cha"], tnc: "SA/8", page: "P.148" },
  { name: "Martial Arts", link: ["rfl"], tnc: "SB/7", page: "P.149" },
  { name: "MedTech", link: ["int"], tnc: "SB/7", page: "P.149" },
  { name: "Melee Weapons", link: ["rfl"], tnc: "SB/7", page: "P.149" },
  { name: "Navigation", link: ["int"], tnc: "SB/7", page: "P.150" },
  { name: "Negotiation", link: ["cha"], tnc: "CB/8", page: "P.150" },
  { name: "Perception", link: ["int"], tnc: "SB/7", page: "P.151" },
  { name: "Piloting", link: ["rfl", "dex"], tnc: "SA/8", page: "P.151" },
  { name: "Prestidigitation", link: ["dex"], tnc: "SB/7", page: "P.152" },
  { name: "Protocol", link: ["wil", "cha"], tnc: "CA/9", page: "P.152" },
  { name: "Running", link: ["rfl"], tnc: "SB/7", page: "P.152" },
  { name: "Science", link: ["int", "wil"], tnc: "CA/9", page: "P.153" },
  { name: "Security Systems", link: ["dex", "int"], tnc: "CA/9", page: "P.153" },
  { name: "Sensor Operations", link: ["int", "wil"], tnc: "CA/9", page: "P.153" },
  { name: "Small Arms", link: ["dex"], tnc: "SB/7", page: "P.153" },
  { name: "Stealth", link: ["rfl", "int"], tnc: "SB/7", page: "P.154" },
  { name: "Strategy", link: ["int", "wil"], tnc: "CA/9", page: "P.154" },
  { name: "Streetwise", link: ["cha"], tnc: "SB/7", page: "P.154" },
  { name: "Support Weapons", link: ["dex"], tnc: "SB/7", page: "P.154" },
  { name: "Surgery", link: ["dex", "int"], tnc: "CA/9", page: "P.154" },
  { name: "Survival", link: ["bod", "int"], tnc: "SB/7", page: "P.156" },
  { name: "Swimming", link: ["str"], tnc: "SB/7", page: "P.156" },
  { name: "Tactics", link: ["int", "wil"], tnc: "CA/9", page: "P.156" },
  { name: "Technician", link: ["dex", "int"], tnc: "CA/9", page: "P.157" },
  { name: "Thrown Weapons", link: ["dex"], tnc: "SB/7", page: "P.158" },
  { name: "Tracking", link: ["int", "wil"], tnc: "CA/9", page: "P.158" },
  { name: "Training", link: ["int", "cha"], tnc: "CA/9", page: "P.159" },
  { name: "Zero-G Operations", link: ["rfl"], tnc: "SB/7", page: "P.159" },
];
*/

/*
export const skillList = [
  { skill: "Acrobatics", link: ["RFL"], tnc: "SB/7" },
  { skill: "Acting", link: ["CHA"], tnc: "CB/8" },
  { skill: "Administration", link: ["INT", "WIL"], tnc: "SA/8" },
  { skill: "Animal Handling", link: ["WIL"], tnc: "SB/7" },
  { skill: "Appraisal", link: ["INT"], tnc: "CB/8" },
  { skill: "Archery", link: ["DEX"], tnc: "SB/7" },
  { skill: "Art", link: ["DEX"], tnc: "CB/8" },
  { skill: "Artillery", link: ["INT", "WIL"], tnc: "SA/8" },
  { skill: "Career", link: ["INT"], tnc: "SB/7" },
  { skill: "Climbing", link: ["DEX"], tnc: "SB/7" },
  { skill: "Communications", link: ["INT"], tnc: "SB/7" },
  { skill: "Computers", link: ["INT"], tnc: "CA/9" },
  { skill: "Cryptography", link: ["INT", "WIL"], tnc: "CA/9" },
  { skill: "Demolitions", link: ["DEX", "INT"], tnc: "CA/9" },
  { skill: "Disguise (+1 kit)", link: ["CHA"], tnc: "SB/7" },
  { skill: "Driving", link: ["RFL", "DEX"], tnc: "SA/8" },
  { skill: "Escape Artist", link: ["STR", "DEX"], tnc: "CA/9" },
  { skill: "Forgery", link: ["DEX", "INT"], tnc: "SA/8" },
  { skill: "Gunnery", link: ["RFL", "DEX"], tnc: "SA/8" },
  { skill: "Interest", link: ["INT"], tnc: "CB/8" },
  { skill: "Interrogation", link: ["WIL", "CHA"], tnc: "CA/9" },
  { skill: "Investigation", link: ["INT", "WIL"], tnc: "CA/9" },
  { skill: "Language", link: ["INT", "CHA"], tnc: "SA/8" },
  { skill: "Leadership", link: ["WIL", "CHA"], tnc: "SA/8" },
  { skill: "Martial Arts", link: ["RFL"], tnc: "SB/7" },
  { skill: "MedTech", link: ["INT"], tnc: "SB/7" },
  { skill: "Melee Weapons", link: ["RFL"], tnc: "SB/7" },
  { skill: "Navigation", link: ["INT"], tnc: "SB/7" },
  { skill: "Negotiation", link: ["CHA"], tnc: "CB/8" },
  { skill: "Perception", link: ["INT"], tnc: "SB/7" },
  { skill: "Piloting", link: ["RFL", "DEX"], tnc: "SA/8" },
  { skill: "Prestidigitation", link: ["DEX"], tnc: "SB/7" },
  { skill: "Protocol", link: ["WIL", "CHA"], tnc: "CA/9" },
  { skill: "Running", link: ["RFL"], tnc: "SB/7" },
  { skill: "Science", link: ["INT", "WIL"], tnc: "CA/9" },
  { skill: "Security Systems", link: ["DEX", "INT"], tnc: "CA/9" },
  { skill: "Sensor Operations", link: ["INT", "WIL"], tnc: "CA/9" },
  { skill: "Small Arms", link: ["DEX"], tnc: "SB/7" },
  { skill: "Stealth", link: ["RFL", "INT"], tnc: "SB/7" },
  { skill: "Strategy", link: ["INT", "WIL"], tnc: "CA/9" },
  { skill: "Streetwise", link: ["CHA"], tnc: "SB/7" },
  { skill: "Support Weapons", link: ["DEX"], tnc: "SB/7" },
  { skill: "Surgery", link: ["DEX", "INT"], tnc: "CA/9" },
  { skill: "Survival", link: ["BOD", "INT"], tnc: "SB/7" },
  { skill: "Swimming", link: ["STR"], tnc: "SB/7" },
  { skill: "Tactics", link: ["INT", "WIL"], tnc: "CA/9" },
  { skill: "Technician", link: ["DEX", "INT"], tnc: "CA/9" },
  { skill: "Thrown Weapons", link: ["DEX"], tnc: "SB/7" },
  { skill: "Tracking", link: ["INT", "WIL"], tnc: "CA/9" },
  { skill: "Training", link: ["INT", "CHA"], tnc: "CA/9" },
  { skill: "Zero-G Operations", link: ["RFL"], tnc: "SB/7" },
];
*/

/*
  const skillList = [
    { skill: "Acrobatics/FreeFall", link: ["RFL"], tnc: "SB/7" },
    { skill: "Acrobatics/Gymnastics", link: ["RFL"], tnc: "SB/7" },
    { skill: "Acting", link: ["CHA"], tnc: "CB/8" },
    { skill: "Administration", link: ["INT", "WIL"], tnc: "SA/8" },
    { skill: "Animal Handling/Herding", link: ["WIL"], tnc: "SB/7" },
    { skill: "Animal Handling/Riding", link: ["WIL"], tnc: "SB/7" },
    { skill: "Animal Handling/Training", link: ["WIL"], tnc: "SB/7" },
    { skill: "Appraisal", link: ["INT"], tnc: "CB/8" },
    { skill: "Archery", link: ["DEX"], tnc: "SB/7" },
    { skill: "Art/Drawing", link: ["DEX"], tnc: "CB/8" },
    { skill: "Art", link: ["DEX"], tnc: "CB/8" },
    { skill: "Art", link: ["DEX"], tnc: "CA/9" },
    { skill: "Art", link: ["DEX"], tnc: "CA/9" },
    { skill: "Art", link: ["DEX"], tnc: "CB/8" },
    { skill: "Artillery", link: ["INT", "WIL"], tnc: "SA/8" },
    { skill: "Career/Soldier", link: ["INT"], tnc: "SB/7" },
    { skill: "Career/Mechwarrior", link: ["INT"], tnc: "SB/7" },
    { skill: "Career", link: ["INT"], tnc: "SB/7" },
    { skill: "Career", link: ["INT"], tnc: "SB/7" },
    { skill: "Career", link: ["INT"], tnc: "SB/7" },
    { skill: "Climbing", link: ["DEX"], tnc: "SB/7" },
    { skill: "Communications/Black Box", link: ["INT"], tnc: "SB/7" },
    { skill: "Communications/Conventional", link: ["INT"], tnc: "SB/7" },
    { skill: "Communications/HPG", link: ["INT"], tnc: "SB/7" },
    { skill: "Computers", link: ["INT"], tnc: "CA/9" },
    { skill: "Cryptography", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Demolitions", link: ["DEX", "INT"], tnc: "CA/9" },
    { skill: "Disguise (+1 kit)", link: ["CHA"], tnc: "SB/7" },
    { skill: "Driving/Ground Vehicles", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Driving/Rail Vehicles", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Driving/Sea Vehicles", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Escape Artist", link: ["STR", "DEX"], tnc: "CA/9" },
    { skill: "Forgery", link: ["DEX", "INT"], tnc: "SA/8" },
    { skill: "Gunnery/Aerospace", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Gunnery/Air Vehicles", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Gunnery/Battlesuit", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Gunnery/Ground Vehicle", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Gunnery/Mech", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Gunnery/ProtoMech", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Gunnery/Sea Vehicle", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Gunnery/Spacecraft", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Gunnery/Turret", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Interest/Writings of Blake", link: ["INT"], tnc: "CB/8" },
    { skill: "Interest/Historical Combat", link: ["INT"], tnc: "CB/8" },
    { skill: "Interest", link: ["INT"], tnc: "CB/8" },
    { skill: "Interest", link: ["INT"], tnc: "CB/8" },
    { skill: "Interest", link: ["INT"], tnc: "CB/8" },
    { skill: "Interrogation", link: ["WIL", "CHA"], tnc: "CA/9" },
    { skill: "Investigation", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Language - English", link: ["INT", "CHA"], tnc: "SA/8" },
    { skill: "Language – Mand/Chinese", link: ["INT", "CHA"], tnc: "SA/8" },
    { skill: "Language", link: ["INT", "CHA"], tnc: "SA/8" },
    { skill: "Language", link: ["INT", "CHA"], tnc: "SA/8" },
    { skill: "Language", link: ["INT", "CHA"], tnc: "SA/8" },
    { skill: "Leadership", link: ["WIL", "CHA"], tnc: "SA/8" },
    { skill: "Martial Arts", link: ["RFL"], tnc: "SB/7" },
    { skill: "MedTech/General", link: ["INT"], tnc: "SB/7" },
    { skill: "MedTech/Veterinary", link: ["INT"], tnc: "SB/7" },
    { skill: "Melee Weapons", link: ["RFL"], tnc: "SB/7" },
    { skill: "Navigation/Air", link: ["INT"], tnc: "SB/7" },
    { skill: "Navigation/Ground", link: ["INT"], tnc: "SB/7" },
    { skill: "Navigation/K-F Jump", link: ["INT"], tnc: "SB/7" },
    { skill: "Navigation/Sea", link: ["INT"], tnc: "SB/7" },
    { skill: "Navigation/Space", link: ["INT"], tnc: "SB/7" },
    { skill: "Negotiation", link: ["CHA"], tnc: "CB/8" },
    { skill: "Perception", link: ["INT"], tnc: "SB/7" },
    { skill: "Piloting/Aerospace", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Piloting/Air Vehicle", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Piloting/Battlesuit", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Piloting/Mech", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Piloting/ProtoMech", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Piloting/Spacecraft", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Prestidigitation/PickPocket", link: ["DEX"], tnc: "SB/7" },
    { skill: "Prestidigitation/Quickdraw", link: ["DEX"], tnc: "SB/7" },
    { skill: "Prestidigitation/Sleight of Hand", link: ["DEX"], tnc: "SB/7" },
    { skill: "Protocol/Capellan", link: ["WIL", "CHA"], tnc: "CA/9" },
    { skill: "Protocol/FedSuns", link: ["WIL", "CHA"], tnc: "CA/9" },
    { skill: "Protocol/Lyran", link: ["WIL", "CHA"], tnc: "CA/9" },
    { skill: "Protocol/Comstar", link: ["WIL", "CHA"], tnc: "CA/9" },
    { skill: "Protocol/Draconis Combine", link: ["WIL", "CHA"], tnc: "CA/9" },
    { skill: "Running", link: ["RFL"], tnc: "SB/7" },
    { skill: "Science/Astrophysics", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Science/Biology", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Science/Chemistry", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Science/Physics", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Science/Engineering", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Security Systems/Electronic", link: ["DEX", "INT"], tnc: "CA/9" },
    { skill: "Security Systems/Mechanical", link: ["DEX", "INT"], tnc: "CA/9" },
    { skill: "Sensor Operations", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Small Arms", link: ["DEX"], tnc: "SB/7" },
    { skill: "Stealth", link: ["RFL", "INT"], tnc: "SB/7" },
    { skill: "Strategy", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Streetwise/Crime", link: ["CHA"], tnc: "SB/7" },
    { skill: "Streetwise/Urban", link: ["CHA"], tnc: "SB/7" },
    { skill: "Streetwise/Underground", link: ["CHA"], tnc: "SB/7" },
    { skill: "Streetwise/Political", link: ["CHA"], tnc: "SB/7" },
    { skill: "Streetwise/Military", link: ["CHA"], tnc: "SB/7" },
    { skill: "Support Weapons", link: ["DEX"], tnc: "SB/7" },
    { skill: "Surgery/General", link: ["DEX", "INT"], tnc: "CA/9" },
    { skill: "Surgery/Veterinary", link: ["DEX", "INT"], tnc: "CA/9" },
    { skill: "Survival/Urban", link: ["BOD", "INT"], tnc: "SB/7" },
    { skill: "Survival/Wilderness", link: ["BOD", "INT"], tnc: "SB/7" },
    { skill: "Swimming", link: ["STR"], tnc: "SB/7" },
    { skill: "Tactics/Infantry", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Tactics/Land", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Tactics/Sea", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Tactics/Air", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Tactics/Space", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Technician/Aeronautics", link: ["DEX", "INT"], tnc: "CA/9" },
    { skill: "Technician/Cybernetics", link: ["DEX", "INT"], tnc: "CA/9" },
    { skill: "Technician/Electronic", link: ["DEX", "INT"], tnc: "CA/9" },
    { skill: "Technician/Jets", link: ["DEX", "INT"], tnc: "CA/9" },
    { skill: "Technician/Mechanical", link: ["DEX", "INT"], tnc: "CA/9" },
    { skill: "Technician/Myomer", link: ["DEX", "INT"], tnc: "CA/9" },
    { skill: "Technician/Nuclear", link: ["DEX", "INT"], tnc: "CA/9" },
    { skill: "Technician/Weapons", link: ["DEX", "INT"], tnc: "CA/9" },
    { skill: "Thrown Weapons/Blades", link: ["DEX"], tnc: "SB/7" },
    { skill: "Thrown Weapons/Blunt Weapons", link: ["DEX"], tnc: "SB/7" },
    { skill: "Tracking/Urban", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Tracking/Wilds", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Training", link: ["INT", "CHA"], tnc: "CA/9" },
    { skill: "Zero-G Operations", link: ["RFL"], tnc: "SB/7" },
  ];

  */
