export const skillList = [
  { skill: "Acrobatics", link: ["RFL"], tnc: "SB/7" },
  { skill: "Acting", link: ["CHA"], tnc: "CB/8" },
  { skill: "Administration", link: ["INT", "WIL"], tnc: "SA/8" },
  { skill: "Animal Handling", link: ["WIL"], tnc: "SB/7" },
  { skill: "Appraisal", link: ["INT"], tnc: "CB/8" },
  { skill: "Archery", link: ["DEX"], tnc: "SB/7" },
  { skill: "Art", link: ["DEX"], tnc: "CB/8" },
  { skill: "Artillery", link: ["INT", "WIL"], tnc: "SA/8" },
  { skill: "Career", link: ["INT"], tnc: "SB/7" },
  { skill: "Climbing", link: ["DEX"], tnc: "SB/7" },
  { skill: "Communications", link: ["INT"], tnc: "SB/7" },
  { skill: "Computers", link: ["INT"], tnc: "CA/9" },
  { skill: "Cryptography", link: ["INT", "WIL"], tnc: "CA/9" },
  { skill: "Demolitions", link: ["DEX", "INT"], tnc: "CA/9" },
  { skill: "Disguise (+1 kit)", link: ["CHA"], tnc: "SB/7" },
  { skill: "Driving", link: ["RFL", "DEX"], tnc: "SA/8" },
  { skill: "Escape Artist", link: ["STR", "DEX"], tnc: "CA/9" },
  { skill: "Forgery", link: ["DEX", "INT"], tnc: "SA/8" },
  { skill: "Gunnery", link: ["RFL", "DEX"], tnc: "SA/8" },
  { skill: "Interest", link: ["INT"], tnc: "CB/8" },
  { skill: "Interrogation", link: ["WIL", "CHA"], tnc: "CA/9" },
  { skill: "Investigation", link: ["INT", "WIL"], tnc: "CA/9" },
  { skill: "Language", link: ["INT", "CHA"], tnc: "SA/8" },
  { skill: "Leadership", link: ["WIL", "CHA"], tnc: "SA/8" },
  { skill: "Martial Arts", link: ["RFL"], tnc: "SB/7" },
  { skill: "MedTech", link: ["INT"], tnc: "SB/7" },
  { skill: "Melee Weapons", link: ["RFL"], tnc: "SB/7" },
  { skill: "Navigation", link: ["INT"], tnc: "SB/7" },
  { skill: "Negotiation", link: ["CHA"], tnc: "CB/8" },
  { skill: "Perception", link: ["INT"], tnc: "SB/7" },
  { skill: "Piloting", link: ["RFL", "DEX"], tnc: "SA/8" },
  { skill: "Prestidigitation", link: ["DEX"], tnc: "SB/7" },
  { skill: "Protocol", link: ["WIL", "CHA"], tnc: "CA/9" },
  { skill: "Running", link: ["RFL"], tnc: "SB/7" },
  { skill: "Science", link: ["INT", "WIL"], tnc: "CA/9" },
  { skill: "Security Systems", link: ["DEX", "INT"], tnc: "CA/9" },
  { skill: "Sensor Operations", link: ["INT", "WIL"], tnc: "CA/9" },
  { skill: "Small Arms", link: ["DEX"], tnc: "SB/7" },
  { skill: "Stealth", link: ["RFL", "INT"], tnc: "SB/7" },
  { skill: "Strategy", link: ["INT", "WIL"], tnc: "CA/9" },
  { skill: "Streetwise", link: ["CHA"], tnc: "SB/7" },
  { skill: "Support Weapons", link: ["DEX"], tnc: "SB/7" },
  { skill: "Surgery", link: ["DEX", "INT"], tnc: "CA/9" },
  { skill: "Survival", link: ["BOD", "INT"], tnc: "SB/7" },
  { skill: "Swimming", link: ["STR"], tnc: "SB/7" },
  { skill: "Tactics", link: ["INT", "WIL"], tnc: "CA/9" },
  { skill: "Technician", link: ["DEX", "INT"], tnc: "CA/9" },
  { skill: "Thrown Weapons", link: ["DEX"], tnc: "SB/7" },
  { skill: "Tracking", link: ["INT", "WIL"], tnc: "CA/9" },
  { skill: "Training", link: ["INT", "CHA"], tnc: "CA/9" },
  { skill: "Zero-G Operations", link: ["RFL"], tnc: "SB/7" },
];

/*
  const skillList = [
    { skill: "Acrobatics/FreeFall", link: ["RFL"], tnc: "SB/7" },
    { skill: "Acrobatics/Gymnastics", link: ["RFL"], tnc: "SB/7" },
    { skill: "Acting", link: ["CHA"], tnc: "CB/8" },
    { skill: "Administration", link: ["INT", "WIL"], tnc: "SA/8" },
    { skill: "Animal Handling/Herding", link: ["WIL"], tnc: "SB/7" },
    { skill: "Animal Handling/Riding", link: ["WIL"], tnc: "SB/7" },
    { skill: "Animal Handling/Training", link: ["WIL"], tnc: "SB/7" },
    { skill: "Appraisal", link: ["INT"], tnc: "CB/8" },
    { skill: "Archery", link: ["DEX"], tnc: "SB/7" },
    { skill: "Art/Drawing", link: ["DEX"], tnc: "CB/8" },
    { skill: "Art", link: ["DEX"], tnc: "CB/8" },
    { skill: "Art", link: ["DEX"], tnc: "CA/9" },
    { skill: "Art", link: ["DEX"], tnc: "CA/9" },
    { skill: "Art", link: ["DEX"], tnc: "CB/8" },
    { skill: "Artillery", link: ["INT", "WIL"], tnc: "SA/8" },
    { skill: "Career/Soldier", link: ["INT"], tnc: "SB/7" },
    { skill: "Career/Mechwarrior", link: ["INT"], tnc: "SB/7" },
    { skill: "Career", link: ["INT"], tnc: "SB/7" },
    { skill: "Career", link: ["INT"], tnc: "SB/7" },
    { skill: "Career", link: ["INT"], tnc: "SB/7" },
    { skill: "Climbing", link: ["DEX"], tnc: "SB/7" },
    { skill: "Communications/Black Box", link: ["INT"], tnc: "SB/7" },
    { skill: "Communications/Conventional", link: ["INT"], tnc: "SB/7" },
    { skill: "Communications/HPG", link: ["INT"], tnc: "SB/7" },
    { skill: "Computers", link: ["INT"], tnc: "CA/9" },
    { skill: "Cryptography", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Demolitions", link: ["DEX", "INT"], tnc: "CA/9" },
    { skill: "Disguise (+1 kit)", link: ["CHA"], tnc: "SB/7" },
    { skill: "Driving/Ground Vehicles", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Driving/Rail Vehicles", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Driving/Sea Vehicles", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Escape Artist", link: ["STR", "DEX"], tnc: "CA/9" },
    { skill: "Forgery", link: ["DEX", "INT"], tnc: "SA/8" },
    { skill: "Gunnery/Aerospace", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Gunnery/Air Vehicles", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Gunnery/Battlesuit", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Gunnery/Ground Vehicle", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Gunnery/Mech", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Gunnery/ProtoMech", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Gunnery/Sea Vehicle", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Gunnery/Spacecraft", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Gunnery/Turret", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Interest/Writings of Blake", link: ["INT"], tnc: "CB/8" },
    { skill: "Interest/Historical Combat", link: ["INT"], tnc: "CB/8" },
    { skill: "Interest", link: ["INT"], tnc: "CB/8" },
    { skill: "Interest", link: ["INT"], tnc: "CB/8" },
    { skill: "Interest", link: ["INT"], tnc: "CB/8" },
    { skill: "Interrogation", link: ["WIL", "CHA"], tnc: "CA/9" },
    { skill: "Investigation", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Language - English", link: ["INT", "CHA"], tnc: "SA/8" },
    { skill: "Language – Mand/Chinese", link: ["INT", "CHA"], tnc: "SA/8" },
    { skill: "Language", link: ["INT", "CHA"], tnc: "SA/8" },
    { skill: "Language", link: ["INT", "CHA"], tnc: "SA/8" },
    { skill: "Language", link: ["INT", "CHA"], tnc: "SA/8" },
    { skill: "Leadership", link: ["WIL", "CHA"], tnc: "SA/8" },
    { skill: "Martial Arts", link: ["RFL"], tnc: "SB/7" },
    { skill: "MedTech/General", link: ["INT"], tnc: "SB/7" },
    { skill: "MedTech/Veterinary", link: ["INT"], tnc: "SB/7" },
    { skill: "Melee Weapons", link: ["RFL"], tnc: "SB/7" },
    { skill: "Navigation/Air", link: ["INT"], tnc: "SB/7" },
    { skill: "Navigation/Ground", link: ["INT"], tnc: "SB/7" },
    { skill: "Navigation/K-F Jump", link: ["INT"], tnc: "SB/7" },
    { skill: "Navigation/Sea", link: ["INT"], tnc: "SB/7" },
    { skill: "Navigation/Space", link: ["INT"], tnc: "SB/7" },
    { skill: "Negotiation", link: ["CHA"], tnc: "CB/8" },
    { skill: "Perception", link: ["INT"], tnc: "SB/7" },
    { skill: "Piloting/Aerospace", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Piloting/Air Vehicle", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Piloting/Battlesuit", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Piloting/Mech", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Piloting/ProtoMech", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Piloting/Spacecraft", link: ["RFL", "DEX"], tnc: "SA/8" },
    { skill: "Prestidigitation/PickPocket", link: ["DEX"], tnc: "SB/7" },
    { skill: "Prestidigitation/Quickdraw", link: ["DEX"], tnc: "SB/7" },
    { skill: "Prestidigitation/Sleight of Hand", link: ["DEX"], tnc: "SB/7" },
    { skill: "Protocol/Capellan", link: ["WIL", "CHA"], tnc: "CA/9" },
    { skill: "Protocol/FedSuns", link: ["WIL", "CHA"], tnc: "CA/9" },
    { skill: "Protocol/Lyran", link: ["WIL", "CHA"], tnc: "CA/9" },
    { skill: "Protocol/Comstar", link: ["WIL", "CHA"], tnc: "CA/9" },
    { skill: "Protocol/Draconis Combine", link: ["WIL", "CHA"], tnc: "CA/9" },
    { skill: "Running", link: ["RFL"], tnc: "SB/7" },
    { skill: "Science/Astrophysics", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Science/Biology", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Science/Chemistry", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Science/Physics", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Science/Engineering", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Security Systems/Electronic", link: ["DEX", "INT"], tnc: "CA/9" },
    { skill: "Security Systems/Mechanical", link: ["DEX", "INT"], tnc: "CA/9" },
    { skill: "Sensor Operations", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Small Arms", link: ["DEX"], tnc: "SB/7" },
    { skill: "Stealth", link: ["RFL", "INT"], tnc: "SB/7" },
    { skill: "Strategy", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Streetwise/Crime", link: ["CHA"], tnc: "SB/7" },
    { skill: "Streetwise/Urban", link: ["CHA"], tnc: "SB/7" },
    { skill: "Streetwise/Underground", link: ["CHA"], tnc: "SB/7" },
    { skill: "Streetwise/Political", link: ["CHA"], tnc: "SB/7" },
    { skill: "Streetwise/Military", link: ["CHA"], tnc: "SB/7" },
    { skill: "Support Weapons", link: ["DEX"], tnc: "SB/7" },
    { skill: "Surgery/General", link: ["DEX", "INT"], tnc: "CA/9" },
    { skill: "Surgery/Veterinary", link: ["DEX", "INT"], tnc: "CA/9" },
    { skill: "Survival/Urban", link: ["BOD", "INT"], tnc: "SB/7" },
    { skill: "Survival/Wilderness", link: ["BOD", "INT"], tnc: "SB/7" },
    { skill: "Swimming", link: ["STR"], tnc: "SB/7" },
    { skill: "Tactics/Infantry", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Tactics/Land", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Tactics/Sea", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Tactics/Air", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Tactics/Space", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Technician/Aeronautics", link: ["DEX", "INT"], tnc: "CA/9" },
    { skill: "Technician/Cybernetics", link: ["DEX", "INT"], tnc: "CA/9" },
    { skill: "Technician/Electronic", link: ["DEX", "INT"], tnc: "CA/9" },
    { skill: "Technician/Jets", link: ["DEX", "INT"], tnc: "CA/9" },
    { skill: "Technician/Mechanical", link: ["DEX", "INT"], tnc: "CA/9" },
    { skill: "Technician/Myomer", link: ["DEX", "INT"], tnc: "CA/9" },
    { skill: "Technician/Nuclear", link: ["DEX", "INT"], tnc: "CA/9" },
    { skill: "Technician/Weapons", link: ["DEX", "INT"], tnc: "CA/9" },
    { skill: "Thrown Weapons/Blades", link: ["DEX"], tnc: "SB/7" },
    { skill: "Thrown Weapons/Blunt Weapons", link: ["DEX"], tnc: "SB/7" },
    { skill: "Tracking/Urban", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Tracking/Wilds", link: ["INT", "WIL"], tnc: "CA/9" },
    { skill: "Training", link: ["INT", "CHA"], tnc: "CA/9" },
    { skill: "Zero-G Operations", link: ["RFL"], tnc: "SB/7" },
  ];

  */
