export const traitList = [
  { id: 0, name: "Alternate ID", type: "alternateId", page: "P.108", min: 2, max: 2 },
  { id: 1, name: "Animal Antipathy", type: "animalAntipathy", page: "P.108", min: -1, max: -1 },
  { id: 2, name: "Ambidextrous", type: "ambidextrous", page: "P.108", min: 2, max: 2 },
  { id: 3, name: "Bloodmark", type: "bloodmark", page: "P.109", min: -5, max: -1 },
  { id: 4, name: "Animal Empathy", type: "animalEmpathy", page: "P.108", min: 1, max: 1 },
  { id: 5, name: "Combat Paralysis", type: "combatParalysis", page: "P.110", min: -4, max: -4 },
  { id: 6, name: "Attractive", type: "attractive", page: "P.108", min: 2, max: 2 },
  { id: 7, name: "Compulsion", type: "compulsion", page: "P.110", min: -5, max: -1 },
  {
    id: 8,
    name: "Citizenship/Trueborn",
    type: "citizenshipTrueborn",
    page: "P.109",
    min: 2,
    max: 2,
  },
  { id: 9, name: "Dark Secret", type: "darkSecret", page: "P.112", min: -5, max: -1 },
  { id: 10, name: "Combat Sense", type: "combatSense", page: "P.110", min: 4, max: 4 },
  { id: 11, name: "Dependent", type: "dependent", page: "P.113", min: -2, max: -1 },
  { id: 12, name: "Connections", type: "connections", page: "P.111", min: 1, max: 10 },
  { id: 13, name: "Enemy", type: "enemy", page: "P.113", min: -10, max: -1 },
  {
    id: 14,
    name: "Exceptional Attribute",
    type: "exceptionalAttribute",
    page: "P.116",
    min: 2,
    max: 2,
  },
  { id: 15, name: "Glass Jaw", type: "glassJaw", page: "P.118", min: -3, max: -3 },
  { id: 16, name: "Fast Learner", type: "fastLearner", page: "P.117", min: 3, max: 3 },
  { id: 17, name: "Gremlins", type: "gremlins", page: "P.118", min: -3, max: -3 },
  { id: 18, name: "Fit", type: "fit", page: "P.117", min: 2, max: 2 },
  { id: 19, name: "Handicap", type: "handicap", page: "P.118", min: -5, max: -1 },
  { id: 20, name: "G-Tolerance", type: "gTolerance", page: "P.118", min: 1, max: 1 },
  { id: 21, name: "Illiterate", type: "illiterate", page: "P.119", min: -1, max: -1 },
  { id: 22, name: "Good Hearing", type: "goodHearing", page: "P.118", min: 1, max: 1 },
  { id: 23, name: "Impatient", type: "impatient", page: "P.119", min: -1, max: -1 },
  { id: 24, name: "Good Vision", type: "goodVision", page: "P.118", min: 1, max: 1 },
  { id: 25, name: "In For Life", type: "inForLife", page: "P.120", min: -3, max: -3 },
  { id: 26, name: "Gregarious", type: "gregarious", page: "P.118", min: 1, max: 1 },
  { id: 27, name: "Introvert", type: "introvert", page: "P.121", min: -1, max: -1 },
  { id: 28, name: "Implant/Prosthetic", type: "implantProsthetic", page: "P.119", min: 1, max: 6 },
  { id: 29, name: "Lost Limb", type: "lostLimb", page: "P.121", min: -5, max: -1 },
  { id: 30, name: "Natural Aptitude", type: "naturalAptitude", page: "P.121", min: 3, max: 5 },
  { id: 31, name: "Poor Hearing", type: "poorHearing", page: "P.122", min: -5, max: -1 },
  { id: 32, name: "Pain Resistance", type: "painResistance", page: "P.121", min: 3, max: 3 },
  { id: 33, name: "Poor Vision", type: "poorVision", page: "P.122", min: -9, max: -2 },
  { id: 34, name: "Patient", type: "patient", page: "P.121", min: 1, max: 1 },
  { id: 35, name: "Slow Learner", type: "slowLearner", page: "P.125", min: -3, max: -3 },
  { id: 36, name: "Phenotype", type: "phenotype", page: "P.121", min: 0, max: 0 },
  { id: 37, name: "TDS", type: "tds", page: "P.127", min: -1, max: -1 },
  { id: 38, name: "Poison Resistance", type: "poisonResistance", page: "P.122", min: 2, max: 2 },
  { id: 39, name: "Unattractive", type: "unattractive", page: "P.128", min: -1, max: -1 },
  { id: 40, name: "Property", type: "property", page: "P.123", min: 1, max: 10 },
  { id: 41, name: "Unlucky", type: "unlucky", page: "P.128", min: -10, max: -2 },
  { id: 42, name: "Rank", type: "rank", page: "P.123", min: 1, max: 15 },
  { id: 43, name: "Sixth Sense", type: "sixthSense", page: "P.125", min: 4, max: 4 },
  { id: 44, name: "Tech Empathy", type: "techEmpathy", page: "P.125", min: 3, max: 3 },
  { id: 45, name: "Title/Bloodname", type: "titleBloodname", page: "P.126", min: 3, max: 10 },
  { id: 46, name: "Toughness", type: "toughness", page: "P.127", min: 3, max: 3 },
  { id: 47, name: "Equipped", type: "equipped", page: "P.116", min: -1, max: 8 },
  { id: 48, name: "Custom Vehicle", type: "customVehicle", page: "P.112", min: 1, max: 6 },
  { id: 49, name: "Design Quirk", type: "designQuirk", page: "P.113", min: -5, max: 5 },
  { id: 50, name: "Vehicle Level", type: "vehicleLevel", page: "P.128", min: 1, max: 12 },
  { id: 51, name: "Wealth", type: "wealth", page: "P.128", min: -1, max: 10 },
];

/*
export const traitList = [
  { name: "Alternate ID", page: "P.108", min: 2, max: 2 },
  { name: "Animal Antipathy", page: "P.108", min: -1, max: -1 },
  { name: "Ambidextrous", page: "P.108", min: 2, max: 2 },
  { name: "Bloodmark", page: "P.109", min: -5, max: -1 },
  { name: "Animal Empathy", page: "P.108", min: 1, max: 1 },
  { name: "Combat Paralysis", page: "P.110", min: -4, max: -4 },
  { name: "Attractive", page: "P.108", min: 2, max: 2 },
  { name: "Compulsion", page: "P.110", min: -5, max: -1 },
  { name: "Citizenship/Trueborn", page: "P.109", min: 2, max: 2 },
  { name: "Dark Secret", page: "P.112", min: -5, max: -1 },
  { name: "Combat Sense", page: "P.110", min: 4, max: 4 },
  { name: "Dependent", page: "P.113", min: -2, max: -1 },
  { name: "Connections", page: "P.111", min: 1, max: 10 },
  { name: "Enemy", page: "P.113", min: -10, max: -1 },
  { name: "Exceptional Attribute", page: "P.116", min: 2, max: 2 },
  { name: "Glass Jaw", page: "P.118", min: -3, max: -3 },
  { name: "Fast Learner", page: "P.117", min: 3, max: 3 },
  { name: "Gremlins", page: "P.118", min: -3, max: -3 },
  { name: "Fit", page: "P.117", min: 2, max: 2 },
  { name: "Handicap", page: "P.118", min: -5, max: -1 },
  { name: "G-Tolerance", page: "P.118", min: 1, max: 1 },
  { name: "Illiterate", page: "P.119", min: -1, max: -1 },
  { name: "Good Hearing", page: "P.118", min: 1, max: 1 },
  { name: "Impatient", page: "P.119", min: -1, max: -1 },
  { name: "Good Vision", page: "P.118", min: 1, max: 1 },
  { name: "In For Life", page: "P.120", min: -3, max: -3 },
  { name: "Gregarious", page: "P.118", min: 1, max: 1 },
  { name: "Introvert", page: "P.121", min: -1, max: -1 },
  { name: "Implant/Prosthetic", page: "P.119", min: 1, max: 6 },
  { name: "Lost Limb", page: "P.121", min: -5, max: -1 },
  { name: "Natural Aptitude", page: "P.121", min: 3, max: 5 },
  { name: "Poor Hearing", page: "P.122", min: -5, max: -1 },
  { name: "Pain Resistance", page: "P.121", min: 3, max: 3 },
  { name: "Poor Vision", page: "P.122", min: -9, max: -2 },
  { name: "Patient", page: "P.121", min: 1, max: 1 },
  { name: "Slow Learner", page: "P.125", min: -3, max: -3 },
  { name: "Phenotype", page: "P.121", min: 0, max: 0 },
  { name: "TDS", page: "P.127", min: -1, max: -1 },
  { name: "Poison Resistance", page: "P.122", min: 2, max: 2 },
  { name: "Unattractive", page: "P.128", min: -1, max: -1 },
  { name: "Property", page: "P.123", min: 1, max: 10 },
  { name: "Unlucky", page: "P.128", min: -10, max: -2 },
  { name: "Rank", page: "P.123", min: 1, max: 15 },
  { name: "Sixth Sense", page: "P.125", min: 4, max: 4 },
  { name: "Tech Empathy", page: "P.125", min: 3, max: 3 },
  { name: "Title/Bloodname", page: "P.126", min: 3, max: 10 },
  { name: "Toughness", page: "P.127", min: 3, max: 3 },
  { name: "Equipped", page: "P.116", min: -1, max: 8 },
  { name: "Custom Vehicle", page: "P.112", min: 1, max: 6 },
  { name: "Design Quirk", page: "P.113", min: -5, max: 5 },
  { name: "Vehicle Level", page: "P.128", min: 1, max: 12 },
  { name: "Wealth", page: "P.128", min: -1, max: 10 },
];
*/

export const opposedTraitsList = [
  {
    positiveTrait: "Animal Empathy",
    positiveTP: "+1",
    negativeTrait: "Animal Antipathy",
    negativeTP: "–1",
  },
  {
    positiveTrait: "Attractive",
    positiveTP: "+2",
    negativeTrait: "Unattractive",
    negativeTP: "–1",
  },
  {
    positiveTrait: "Combat Sense",
    positiveTP: "+4",
    negativeTrait: "Combat Paralysis",
    negativeTP: "–4",
  },
  {
    positiveTrait: "Fast Learner",
    positiveTP: "+3",
    negativeTrait: "Slow Learner",
    negativeTP: "–3",
  },
  { positiveTrait: "Fit", positiveTP: "+2", negativeTrait: "Handicap", negativeTP: "–[1 to 5]" },
  {
    positiveTrait: "Good Hearing",
    positiveTP: "+1",
    negativeTrait: "Poor Hearing",
    negativeTP: "–[1 to 5]",
  },
  {
    positiveTrait: "Good Vision",
    positiveTP: "+1",
    negativeTrait: "Poor Vision",
    negativeTP: "–[1 to 9]",
  },
  { positiveTrait: "Gregarious", positiveTP: "+1", negativeTrait: "Introvert", negativeTP: "–1" },
  {
    positiveTrait: "4+ Levels in a Language Skill",
    positiveTP: "",
    negativeTrait: "Illiterate",
    negativeTP: "–1",
  },
  { positiveTrait: "Patient", positiveTP: "+1", negativeTrait: "Impatient", negativeTP: "–1" },
  { positiveTrait: "Tech Empathy", positiveTP: "+3", negativeTrait: "Gremlins", negativeTP: "–3" },
  { positiveTrait: "Toughness", positiveTP: "+3", negativeTrait: "Glass Jaw", negativeTP: "–3" },
];
